/**
 * AI Output Validator
 * 
 * Critical safety layer that verifies semantic transformations generated by the AI
 * do not violate the deterministic usage constraints.
 */

import { Context } from './context';
import { SemanticRefactorResult } from './aiService';

export interface ValidationResult {
    isValid: boolean;
    errors: string[];
}

/**
 * Validates the AI's generated refactor against deterministic rules.
 * 
 * @param context - The original usage context constraints
 * @param targetDS - The data structure the AI was supposed to migrate to
 * @param aiOutput - The generated code and metadata
 */
export function validateRefactor(context: Context, targetDS: string, aiOutput: SemanticRefactorResult): ValidationResult {
    const errors: string[] = [];

    // Ensure AI actually returned code
    if (!aiOutput.new_code || aiOutput.new_code.trim() === '') {
        return { isValid: false, errors: ['AI failed to return modified code.'] };
    }

    const cleanTarget = targetDS.replace('std::', '');
    const isUnordered = cleanTarget.startsWith('unordered_');

    // Rule 1: If context uses index access (v[i]), target cannot be unordered map/set without rewriting it completely.
    // We check if the AI hallucinated and left index access in when migrating to an unordered structure.
    if (context.usesIndexAccess && isUnordered) {
        // Did the AI leave v[i] in the code?
        const indexRegex = /\[(.*?)\]/g;
        if (indexRegex.test(aiOutput.new_code)) {
            // Note: For unordered_map, operator[] IS valid, but for unordered_set it is NOT.
            if (cleanTarget === 'unordered_set') {
                errors.push(`Unsafe transformation: AI left index access operations on an unordered_set.`);
            }
        }
    }

    // Rule 2: If context requires ordering, target cannot be unordered
    if (context.hasOrdering && isUnordered) {
        errors.push(`Unsafe transformation: Context requires ordering (e.g. sort, lower_bound), but target is unordered.`);
    }

    // Rule 3: Advanced DS Rules
    if (cleanTarget === 'priority_queue') {
        if (context.usesIndexAccess) {
            errors.push('Unsafe transformation: priority_queue does not support random index access, but context requires it.');
        }
    } else if (cleanTarget === 'Trie') {
        if (!aiOutput.new_code.includes('string') && !aiOutput.new_code.includes('char')) {
            errors.push('Unsafe transformation: AI generated a Trie but no string-based operations were found in the output.');
        }
    } else if (cleanTarget === 'Segment Tree') {
        // Verify the AI produced a proper segment tree with array-based storage
        // Standard implementations use flat arrays (tree[], seg[], vector<int> tree)
        const hasArrayStorage = aiOutput.new_code.includes('vector') || 
                                aiOutput.new_code.includes('[') ||
                                aiOutput.new_code.includes('array');
        const hasSegTreeOps = aiOutput.new_code.includes('build') || 
                              aiOutput.new_code.includes('update') || 
                              aiOutput.new_code.includes('query');
        if (!hasArrayStorage) {
            errors.push('Unsafe transformation: AI generated a Segment Tree but lost the array-based storage layer.');
        }
        if (!hasSegTreeOps) {
            errors.push('Unsafe transformation: AI generated a Segment Tree but missing core operations (build/update/query).');
        }
    } else if (cleanTarget === 'Skip List') {
        if (!aiOutput.new_code.includes('struct') && !aiOutput.new_code.includes('class')) {
            errors.push('Unsafe transformation: AI generated a Skip List but no node structure was found.');
        }
    }

    return {
        isValid: errors.length === 0,
        errors
    };
}
