/**
 * AI Output Validator
 * 
 * Critical safety layer that verifies semantic transformations generated by the AI
 * do not violate the deterministic usage constraints.
 */

import { Context } from './context';
import { SemanticRefactorResult } from './aiService';

export interface ValidationResult {
    isValid: boolean;
    errors: string[];
}

/**
 * Validates the AI's generated refactor against deterministic rules.
 * 
 * @param context - The original usage context constraints
 * @param targetDS - The data structure the AI was supposed to migrate to
 * @param aiOutput - The generated code and metadata
 */
export function validateRefactor(context: Context, targetDS: string, aiOutput: SemanticRefactorResult): ValidationResult {
    const errors: string[] = [];

    // Ensure AI actually returned code
    if (!aiOutput.new_code || aiOutput.new_code.trim() === '') {
        return { isValid: false, errors: ['AI failed to return modified code.'] };
    }

    const cleanTarget = targetDS.replace('std::', '');
    const isUnordered = cleanTarget.startsWith('unordered_');

    // Rule 1: If context uses index access (v[i]), target cannot be unordered map/set without rewriting it completely.
    // We check if the AI hallucinated and left index access in when migrating to an unordered structure.
    if (context.usesIndexAccess && isUnordered) {
        // Did the AI leave v[i] in the code?
        const indexRegex = /\[(.*?)\]/g;
        if (indexRegex.test(aiOutput.new_code)) {
            // Note: For unordered_map, operator[] IS valid, but for unordered_set it is NOT.
            if (cleanTarget === 'unordered_set') {
                errors.push(`Unsafe transformation: AI left index access operations on an unordered_set.`);
            }
        }
    }

    // Rule 2: If context requires ordering, target cannot be unordered
    if (context.hasOrdering && isUnordered) {
        errors.push(`Unsafe transformation: Context requires ordering (e.g. sort, lower_bound), but target is unordered.`);
    }

    return {
        isValid: errors.length === 0,
        errors
    };
}
